version: '3.1'

services:

    api:
        image: 'insta-api'
        ports:
            - '8080:8080'
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/instadb
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=12345
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    db:
        image: 'postgres'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=instadb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
